services:
  pokenaetemplate-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=PokenaeTemplate;User Id=sa;Password=${MSSQL_SA_PASSWORD:-Sql1Password};TrustServerCertificate=True;
    ports:
      - "${APP_HTTP_PORT:-18180}:8080"
      - "${APP_HTTPS_PORT:-18181}:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
